// Bundled Registry: known AI coding-agent CLIs.
// id: unique key, label: display name, bin: binary to probe on PATH, args: default invoke args.
export const REGISTRY = [
  { id: 'claude', label: 'Claude Code', bin: 'claude', args: [] },
  { id: 'codex', label: 'Codex CLI', bin: 'codex', args: [] },
  { id: 'opencode', label: 'opencode', bin: 'opencode', args: [] },
  { id: 'omp', label: 'omp', bin: 'omp', args: [] },
  { id: 'pi', label: 'pi', bin: 'pi', args: [] },
  { id: 'prime-agent', label: 'Prime Agent', bin: 'prime-agent', args: [] },
  { id: 'aider', label: 'Aider', bin: 'aider', args: [] },
  { id: 'gemini', label: 'Gemini CLI', bin: 'gemini', args: [] },
  { id: 'continue', label: 'Continue', bin: 'cn', args: [] },
  { id: 'goose', label: 'Goose', bin: 'goose', args: [] },
  { id: 'cursor-agent', label: 'Cursor Agent', bin: 'cursor-agent', args: [] },
  { id: 'copilot', label: 'GitHub Copilot CLI', bin: 'copilot', args: [] },
  { id: 'q', label: 'Amazon Q Developer', bin: 'q', args: [] },
  { id: 'cody', label: 'Sourcegraph Cody', bin: 'cody', args: [] },
  { id: 'hermes', label: 'Hermes', bin: 'hermes', args: [] },
  { id: 'antigravity', label: 'Antigravity', bin: 'agy', args: [] },
  { id: 'poolside', label: 'Poolside', bin: 'pool', args: [] },
  { id: 'forge', label: 'Forge', bin: 'forge', args: [] },
  { id: 'codewhale', label: 'CodeWhale', bin: 'codewhale', args: [] },
  { id: 'command-code', label: 'Command Code', bin: 'cmdc', args: [] },
  { id: 'freebuff', label: 'Freebuff', bin: 'freebuff', args: [] },
  { id: 'reasonix', label: 'Reasonix', bin: 'reasonix', args: [] },
  { id: 'kilo', label: 'Kilo', bin: 'kilo', args: [] },
  { id: 'crush', label: 'Crush', bin: 'crush', args: [] },
  { id: 'droid', label: 'Droid', bin: 'droid', args: [] },
  { id: 'fx', label: 'fx', bin: 'fx', args: [] },
  { id: 'grok', label: 'Grok Build', bin: 'grok', args: [] },
  { id: 'cline', label: 'Cline', bin: 'cline', args: [] },
  { id: 'openhands', label: 'OpenHands', bin: 'openhands', args: [] },
  { id: 'open-interpreter', label: 'Open Interpreter', bin: 'interpreter', args: [] },
  { id: 'amp', label: 'Amp', bin: 'amp', args: [] },
  { id: 'qwen-code', label: 'Qwen Code', bin: 'qwen', args: [] },
  { id: 'gpt-engineer', label: 'gpt-engineer', bin: 'gpt-engineer', args: [] },
];

